vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /images
            upload_destination: "%kernel.project_dir%/public/images"
            delete_on_update: false
            delete_on_remove: false
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options:
                    property: "slug"
